"""empty message

Revision ID: 957b28b51859
Revises: eb62416d64a3
Create Date: 2023-07-24 04:11:48.273807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957b28b51859'
down_revision = 'eb62416d64a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
